window.POOL_TESTS = [
  {
    "date": "2026-05-23",
    "source": "Leslie's store test",
    "confidence": "Exact",
    "time": "PM",
    "fc": 0.16,
    "tc": 0.81,
    "ph": 8.0,
    "ta": 75,
    "ch": 548,
    "cya": 191,
    "iron": 0.0,
    "copper": 0.2,
    "phosphates": 0,
    "tds": 3500,
    "notes": "Pre-drain/refill baseline. High CYA and CH."
  },
  {
    "date": "2026-05-25",
    "source": "Leslie's store test",
    "confidence": "Exact",
    "time": "",
    "fc": 0.25,
    "tc": 2.97,
    "ph": 7.9,
    "ta": 156,
    "ch": 191,
    "cya": 42,
    "iron": 0.0,
    "copper": 0.2,
    "phosphates": 0,
    "tds": 700,
    "notes": "After major drain/refill."
  },
  {
    "date": "2026-06-01",
    "source": "Leslie's store test",
    "confidence": "Exact",
    "time": "",
    "fc": 3.88,
    "tc": 3.88,
    "ph": 8.0,
    "ta": 119,
    "ch": 170,
    "cya": 44,
    "iron": 0.0,
    "copper": 0.3,
    "phosphates": 553,
    "tds": 800,
    "notes": "Clear water. FC in range, pH slightly high, CH low for PebbleTec."
  },
  {
    "date": "2026-06-06",
    "source": "Strip (old 4-way bottle)",
    "confidence": "Approx",
    "time": "Morning",
    "fc": 5.0,
    "tc": null,
    "ph": 7.8,
    "ta": 120,
    "ch": null,
    "cya": 40,
    "iron": null,
    "copper": null,
    "phosphates": null,
    "tds": null,
    "notes": "Approx from image/color read."
  },
  {
    "date": "2026-06-06",
    "source": "Strip (new multi-parameter bottle)",
    "confidence": "Approx",
    "time": "Evening",
    "fc": 2.0,
    "tc": 3.0,
    "ph": 7.5,
    "ta": 100,
    "ch": null,
    "cya": 40,
    "iron": null,
    "copper": null,
    "phosphates": null,
    "tds": null,
    "notes": "Approx from image/color read; new strip style."
  },
  {
    "date": "2026-06-09",
    "source": "Strip (new multi-parameter bottle)",
    "confidence": "Approx",
    "time": "Evening",
    "fc": 1.0,
    "tc": 1.0,
    "ph": 7.8,
    "ta": 80,
    "ch": null,
    "cya": 40,
    "iron": null,
    "copper": null,
    "phosphates": null,
    "tds": null,
    "notes": "Average of 4 photos. Added 1/2 gallon of 12.5% liquid chlorine after this test."
  },
  {
    "date": "2026-06-15",
    "source": "Strip (new multi-parameter bottle)",
    "confidence": "Approx",
    "time": "",
    "fc": 0.75,
    "tc": 1.0,
    "ph": 7.8,
    "ta": 80,
    "ch": null,
    "cya": 40,
    "iron": null,
    "copper": null,
    "phosphates": null,
    "tds": null,
    "notes": "Average of 3 photos. Total hardness on strip approx 500 ppm."
  },
  {
    "date": "2026-06-15",
    "source": "Strip (new multi-parameter bottle)",
    "confidence": "Approx",
    "time": "Evening",
    "fc": 1.0,
    "tc": 1.0,
    "ph": 7.8,
    "ta": 80,
    "ch": null,
    "cya": 40,
    "iron": null,
    "copper": null,
    "phosphates": null,
    "tds": null,
    "notes": "Average of 4 photos. Added 1/2 gallon of 12.5% liquid chlorine after this test."
  },
  {
    "date": "2026-06-15",
    "source": "Strip (new multi-parameter bottle)",
    "confidence": "Approx",
    "time": "Today",
    "fc": 0.5,
    "tc": 1.0,
    "ph": 7.8,
    "ta": 80,
    "ch": null,
    "cya": 40,
    "iron": null,
    "copper": null,
    "phosphates": null,
    "tds": null,
    "notes": "Latest strip photos. Total hardness looks roughly 500 ppm. Free chlorine appears low again."
  }
];
